apiVersion: apps/v1
kind: Deployment 
metadata: 
    name: my_nginx_deployment
spec: 
    replicas: 5
    selectors:
        matchLabels:
            app: nginx
    template: 
        metadata: 
           labels:
              app: nginx     
        spec: 
           containers:
           - name: nginx
             image: nginx
             ports:
              - containerPort: 80
